/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calendar;

import javax.swing.*;

/**
 *
 * @author berkay
 */
public class EventsDateBaseManipulation extends javax.swing.JFrame {

    private DataBase database = new DataBase();
    private String[] years = new String[100];
    private String[] mounths = new String[12];
    private String[] days = new String[31];
    private String[] hours = new String[25];
    private String[] minute = new String[61];
    private String startingDate;

    public EventsDateBaseManipulation(String startingDate) {
        initComponents();
        this.startingDate = startingDate;
        if (!"".equals(startingDate)) {
            startingDateLabel.setVisible(false);
            startingDayComboBox.setVisible(false);
            startingMounthComboBox.setVisible(false);
            startingYearComboBox.setVisible(false);
            startingHourComboBox.setVisible(false);
            startingMinuteComboBox.setVisible(false);
        }
        int i;
        for (i = 0; i < 100; i++) {
            years[i] = Integer.toString(i + 2010);
        }
        for (i = 0; i < 31; i++) {
            if (i < 10) {
                days[i] = "0" + Integer.toString(i + 1);
            } else {
                days[i] = Integer.toString(i + 1);
            }

        }
        for (i = 0; i < 12; i++) {
            if (i < 10) {
                mounths[i] = "0" + Integer.toString(i + 1);
            } else {
                mounths[i] = Integer.toString(i + 1);
            }

        }
        for (i = 0; i < 24; i++) {
            if (i < 10) {
                hours[i] = "0" + Integer.toString(i);
            } else {
                hours[i] = Integer.toString(i);
            }

        }
        for (i = 0; i < 60; i++) {
            if (i < 10) {
                minute[i] = "0" + Integer.toString(i);
            } else {
                minute[i] = Integer.toString(i);
            }

        }
        final DefaultComboBoxModel startingDayBoxModel = new DefaultComboBoxModel(days);
        final DefaultComboBoxModel startingMounthBoxModel = new DefaultComboBoxModel(mounths);
        final DefaultComboBoxModel startingYearBoxModel = new DefaultComboBoxModel(years);
        final DefaultComboBoxModel dueDayBoxModel = new DefaultComboBoxModel(days);
        final DefaultComboBoxModel dueMounthBoxModel = new DefaultComboBoxModel(mounths);
        final DefaultComboBoxModel dueYearBoxModel = new DefaultComboBoxModel(years);
        final DefaultComboBoxModel startingHourBoxModel = new DefaultComboBoxModel(hours);
        final DefaultComboBoxModel startingMinuteBoxModel = new DefaultComboBoxModel(minute);
        final DefaultComboBoxModel dueHourBoxModel = new DefaultComboBoxModel(hours);
        final DefaultComboBoxModel dueMinuteBoxModel = new DefaultComboBoxModel(minute);

        startingDayComboBox.setModel(startingDayBoxModel);
        startingMounthComboBox.setModel(startingMounthBoxModel);
        startingYearComboBox.setModel(startingYearBoxModel);
        dueDayComboBox.setModel(dueDayBoxModel);
        dueMounthComboBox.setModel(dueMounthBoxModel);
        dueYearComboBox.setModel(dueYearBoxModel);
        startingHourComboBox.setModel(startingHourBoxModel);
        startingMinuteComboBox.setModel(startingMinuteBoxModel);
        dueHourComboBox.setModel(dueHourBoxModel);
        dueMinuteComboBox.setModel(dueMinuteBoxModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        locationTextField = new javax.swing.JTextField();
        startingYearComboBox = new javax.swing.JComboBox<>();
        startingMounthComboBox = new javax.swing.JComboBox<>();
        startingDayComboBox = new javax.swing.JComboBox<>();
        startingDateLabel = new javax.swing.JLabel();
        dueYearComboBox = new javax.swing.JComboBox<>();
        dueMounthComboBox = new javax.swing.JComboBox<>();
        dueDayComboBox = new javax.swing.JComboBox<>();
        dueDateLabel = new javax.swing.JLabel();
        addEventButton = new javax.swing.JButton();
        startingHourComboBox = new javax.swing.JComboBox<>();
        startingMinuteComboBox = new javax.swing.JComboBox<>();
        dueHourComboBox = new javax.swing.JComboBox<>();
        dueMinuteComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        nameLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        nameLabel.setText("Name                 :");

        locationLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        locationLabel.setText("Location           :");

        locationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationTextFieldActionPerformed(evt);
            }
        });

        startingYearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startingYearComboBoxActionPerformed(evt);
            }
        });

        startingMounthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        startingDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        startingDateLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        startingDateLabel.setText("Starting Date :");

        dueYearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dueMounthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dueDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dueDateLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        dueDateLabel.setText("Due Date        : ");

        addEventButton.setText("Add Event");
        addEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEventButtonActionPerformed(evt);
            }
        });

        startingHourComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        startingMinuteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dueHourComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dueMinuteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dueDateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(startingDateLabel)
                        .addComponent(locationLabel)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(locationTextField)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dueYearComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startingYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startingMounthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(startingDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dueMounthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dueDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startingHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startingMinuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dueHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dueMinuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addEventButton)
                .addGap(372, 372, 372))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startingYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startingMounthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startingDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startingDateLabel)
                    .addComponent(startingHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startingMinuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dueYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dueMounthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dueDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dueDateLabel)
                    .addComponent(dueHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dueMinuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(addEventButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void locationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationTextFieldActionPerformed

    private void addEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEventButtonActionPerformed
        String name = nameTextField.getText();
        String location = locationTextField.getText();
        boolean result = false;

        String dueDate = dueYearComboBox.getSelectedItem().toString() + "-"
                + dueMounthComboBox.getSelectedItem().toString() + "-"
                + dueDayComboBox.getSelectedItem().toString() + " "
                + dueHourComboBox.getSelectedItem().toString() + ":"
                + dueMinuteComboBox.getSelectedItem().toString() + ":" + "00";
        if (this.startingDate.equals("")) {
            String startingDate = startingYearComboBox.getSelectedItem().toString() + "-"
                    + startingMounthComboBox.getSelectedItem().toString() + "-"
                    + startingDayComboBox.getSelectedItem().toString() + " "
                    + startingHourComboBox.getSelectedItem().toString() + ":"
                    + startingMinuteComboBox.getSelectedItem().toString() + ":" + "00";
            result = database.addEvent(name, location, startingDate, dueDate);
        } else {
            result = database.addEvent(name, location, this.startingDate, dueDate);
        }

        if (result) {
            setVisible(false);
        }
        // adding element to events  
    }//GEN-LAST:event_addEventButtonActionPerformed

    private void startingYearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startingYearComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startingYearComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEventButton;
    private javax.swing.JLabel dueDateLabel;
    private javax.swing.JComboBox<String> dueDayComboBox;
    private javax.swing.JComboBox<String> dueHourComboBox;
    private javax.swing.JComboBox<String> dueMinuteComboBox;
    private javax.swing.JComboBox<String> dueMounthComboBox;
    private javax.swing.JComboBox<String> dueYearComboBox;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel startingDateLabel;
    private javax.swing.JComboBox<String> startingDayComboBox;
    private javax.swing.JComboBox<String> startingHourComboBox;
    private javax.swing.JComboBox<String> startingMinuteComboBox;
    private javax.swing.JComboBox<String> startingMounthComboBox;
    private javax.swing.JComboBox<String> startingYearComboBox;
    // End of variables declaration//GEN-END:variables
}
