/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calendar;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JButton;

/**
 *
 * @author berkay
 */
public class MainGUI extends javax.swing.JFrame {

    public CurrentDate currentDate;
    public JButton[] listofDays;

    public MainGUI() {
        initComponents();
        currentDate = new CurrentDate();
        JButton[] listOfDays = {monday1, tuesday1, wednesday1, thursday1, friday1,
            saturday1, sunday1, monday2, tuesday2, wednesday2, thursday2, friday2,
            saturday2, sunday2, monday3, tuesday3, wednesday3, thursday3, friday3,
            saturday3, sunday3, monday4, tuesday4, wednesday4, thursday4, friday4,
            saturday4, sunday4, monday5, tuesday5, wednesday5, thursday5, friday5,
            saturday5, sunday5, monday4, tuesday4, wednesday4, thursday4, friday4,
            saturday4, sunday6, monday6, tuesday6, wednesday6, thursday6, friday6,
            saturday6, sunday6};
        this.listofDays = listOfDays.clone();
        prepareDaysInterface(listOfDays);
        todayDateLabel.setText(currentDate.getDayNum()+"/"+currentDate.getCurrentMonth()+"/"+currentDate.getCurrentYear());
        

    }

    public void prepareDaysInterface(JButton[] listOfDays) {

        ArrayList<JButton> buttons = new ArrayList<>(Arrays.asList(listOfDays));

        String day = currentDate.getBeginningOfMonth();

        switch (day) {
            case "Tue": {
                buttons.remove(monday1);

                break;
            }
            case "Wed": {
                buttons.remove(monday1);
                buttons.remove(tuesday1);

                break;
            }
            case "Thu": {
                buttons.remove(monday1);
                buttons.remove(tuesday1);
                buttons.remove(wednesday1);

                break;
            }
            case "Fri": {
                buttons.remove(monday1);
                buttons.remove(tuesday1);
                buttons.remove(wednesday1);
                buttons.remove(thursday1);

                break;
            }
            case "Sat": {
                buttons.remove(monday1);
                buttons.remove(tuesday1);
                buttons.remove(wednesday1);
                buttons.remove(thursday1);
                buttons.remove(friday1);

                break;
            }
            case "Sun": {
                buttons.remove(monday1);
                buttons.remove(tuesday1);
                buttons.remove(wednesday1);
                buttons.remove(thursday1);
                buttons.remove(friday1);
                buttons.remove(saturday1);

                break;
            }
        }
        clearButtonsName(listOfDays); // clearing button's text
        setButtonsName(buttons, currentDate); // Setting buttons name 
        monthLabel.setText(currentDate.getMonth()+"/"+currentDate.getYear());
        
    }

    private void clearButtonsName(JButton[] buttons) {

        for (JButton b : buttons) {
            b.setText("");
            b.setForeground(Color.black);
        }
    }

    private void setButtonsName(ArrayList<JButton> button, CurrentDate currentDate) {

        int dayNum = Integer.parseInt(currentDate.getDayNum());

        for (int i = 0; i < currentDate.getActualMaximum(); i++) {

            button.get(i).setText(Integer.toString(i + 1));
            button.get(i).setFont(new Font("Arial", Font.PLAIN, 40)); // set font

        }
        if (currentDate.getCurrentMonth().equals(currentDate.getMonth())) {
            button.get(dayNum - 1).setForeground(Color.red);
        }

    }

    private void createNewDayGui(JButton button) {

        String day = button.getText();

        if (!day.equals("")) {
            DayGUI gui = new DayGUI(day, currentDate.getMonth(), currentDate.getYear());
            gui.buildGoals();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        todayPanel = new javax.swing.JPanel();
        todayLabel = new javax.swing.JLabel();
        todayDateLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        daysOfMonth = new javax.swing.JPanel();
        sunday3 = new javax.swing.JButton();
        monday2 = new javax.swing.JButton();
        wednesday2 = new javax.swing.JButton();
        monday1 = new javax.swing.JButton();
        tuesday2 = new javax.swing.JButton();
        saturday2 = new javax.swing.JButton();
        friday2 = new javax.swing.JButton();
        thursday2 = new javax.swing.JButton();
        wednesday1 = new javax.swing.JButton();
        sunday2 = new javax.swing.JButton();
        tuesday1 = new javax.swing.JButton();
        monday4 = new javax.swing.JButton();
        wednesday4 = new javax.swing.JButton();
        tuesday4 = new javax.swing.JButton();
        saturday4 = new javax.swing.JButton();
        saturday1 = new javax.swing.JButton();
        friday4 = new javax.swing.JButton();
        friday1 = new javax.swing.JButton();
        thursday4 = new javax.swing.JButton();
        thursday1 = new javax.swing.JButton();
        sunday1 = new javax.swing.JButton();
        sunday4 = new javax.swing.JButton();
        monday3 = new javax.swing.JButton();
        wednesday3 = new javax.swing.JButton();
        tuesday3 = new javax.swing.JButton();
        saturday3 = new javax.swing.JButton();
        friday3 = new javax.swing.JButton();
        thursday3 = new javax.swing.JButton();
        firstDay = new javax.swing.JLabel();
        secondDay = new javax.swing.JLabel();
        thirdDay = new javax.swing.JLabel();
        forthDay = new javax.swing.JLabel();
        fifthDay = new javax.swing.JLabel();
        sixthDay = new javax.swing.JLabel();
        ninethday = new javax.swing.JLabel();
        monday5 = new javax.swing.JButton();
        wednesday5 = new javax.swing.JButton();
        tuesday5 = new javax.swing.JButton();
        saturday5 = new javax.swing.JButton();
        friday5 = new javax.swing.JButton();
        thursday5 = new javax.swing.JButton();
        sunday5 = new javax.swing.JButton();
        friday6 = new javax.swing.JButton();
        thursday6 = new javax.swing.JButton();
        sunday6 = new javax.swing.JButton();
        monday6 = new javax.swing.JButton();
        wednesday6 = new javax.swing.JButton();
        tuesday6 = new javax.swing.JButton();
        saturday6 = new javax.swing.JButton();
        monthLabel = new javax.swing.JLabel();
        monthNextButton = new javax.swing.JButton();
        monthPrevButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calendar");
        setBackground(new java.awt.Color(204, 255, 255));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);

        todayPanel.setBackground(new java.awt.Color(153, 255, 255));

        todayLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        todayLabel.setText("TODAY");

        todayDateLabel.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        todayDateLabel.setText("Today Date ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout todayPanelLayout = new javax.swing.GroupLayout(todayPanel);
        todayPanel.setLayout(todayPanelLayout);
        todayPanelLayout.setHorizontalGroup(
            todayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todayPanelLayout.createSequentialGroup()
                .addGroup(todayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(todayPanelLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(todayDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(todayPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(todayPanelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(todayLabel)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        todayPanelLayout.setVerticalGroup(
            todayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(todayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(todayDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        daysOfMonth.setBackground(new java.awt.Color(255, 0, 0));

        sunday3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunday3ActionPerformed(evt);
            }
        });

        monday2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monday2ActionPerformed(evt);
            }
        });

        wednesday2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesday2ActionPerformed(evt);
            }
        });

        monday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monday1ActionPerformed(evt);
            }
        });

        tuesday2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesday2ActionPerformed(evt);
            }
        });

        saturday2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturday2ActionPerformed(evt);
            }
        });

        friday2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friday2ActionPerformed(evt);
            }
        });

        thursday2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursday2ActionPerformed(evt);
            }
        });

        wednesday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesday1ActionPerformed(evt);
            }
        });

        sunday2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunday2ActionPerformed(evt);
            }
        });

        tuesday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesday1ActionPerformed(evt);
            }
        });

        monday4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monday4ActionPerformed(evt);
            }
        });

        wednesday4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesday4ActionPerformed(evt);
            }
        });

        tuesday4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesday4ActionPerformed(evt);
            }
        });

        saturday4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturday4ActionPerformed(evt);
            }
        });

        saturday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturday1ActionPerformed(evt);
            }
        });

        friday4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friday4ActionPerformed(evt);
            }
        });

        friday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friday1ActionPerformed(evt);
            }
        });

        thursday4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursday4ActionPerformed(evt);
            }
        });

        thursday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursday1ActionPerformed(evt);
            }
        });

        sunday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunday1ActionPerformed(evt);
            }
        });

        sunday4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunday4ActionPerformed(evt);
            }
        });

        monday3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monday3ActionPerformed(evt);
            }
        });

        wednesday3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesday3ActionPerformed(evt);
            }
        });

        tuesday3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesday3ActionPerformed(evt);
            }
        });

        saturday3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturday3ActionPerformed(evt);
            }
        });

        friday3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friday3ActionPerformed(evt);
            }
        });

        thursday3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursday3ActionPerformed(evt);
            }
        });

        firstDay.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        firstDay.setForeground(new java.awt.Color(0, 0, 0));
        firstDay.setText("Monday");

        secondDay.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        secondDay.setForeground(new java.awt.Color(0, 0, 0));
        secondDay.setText("Tuesday");

        thirdDay.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        thirdDay.setForeground(new java.awt.Color(0, 0, 0));
        thirdDay.setText("Wednesday");

        forthDay.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        forthDay.setForeground(new java.awt.Color(0, 0, 0));
        forthDay.setText("Thursday");

        fifthDay.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        fifthDay.setForeground(new java.awt.Color(0, 0, 0));
        fifthDay.setText("Friday");

        sixthDay.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        sixthDay.setForeground(new java.awt.Color(0, 0, 0));
        sixthDay.setText("Sunday");

        ninethday.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ninethday.setForeground(new java.awt.Color(0, 0, 0));
        ninethday.setText("Saturday");

        monday5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monday5ActionPerformed(evt);
            }
        });

        wednesday5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesday5ActionPerformed(evt);
            }
        });

        tuesday5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesday5ActionPerformed(evt);
            }
        });

        saturday5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturday5ActionPerformed(evt);
            }
        });

        friday5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friday5ActionPerformed(evt);
            }
        });

        thursday5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursday5ActionPerformed(evt);
            }
        });

        sunday5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunday5ActionPerformed(evt);
            }
        });

        friday6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friday6ActionPerformed(evt);
            }
        });

        thursday6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursday6ActionPerformed(evt);
            }
        });

        sunday6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunday6ActionPerformed(evt);
            }
        });

        monday6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monday6ActionPerformed(evt);
            }
        });

        wednesday6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesday6ActionPerformed(evt);
            }
        });

        tuesday6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesday6ActionPerformed(evt);
            }
        });

        saturday6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturday6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout daysOfMonthLayout = new javax.swing.GroupLayout(daysOfMonth);
        daysOfMonth.setLayout(daysOfMonthLayout);
        daysOfMonthLayout.setHorizontalGroup(
            daysOfMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daysOfMonthLayout.createSequentialGroup()
                .addGroup(daysOfMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(daysOfMonthLayout.createSequentialGroup()
                        .addGroup(daysOfMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(daysOfMonthLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(firstDay)
                                .addGap(38, 38, 38)
                                .addComponent(secondDay)
                                .addGap(24, 24, 24)
                                .addComponent(thirdDay)
                                .addGap(18, 18, 18)
                                .addComponent(forthDay)
                                .addGap(38, 38, 38)
                                .addComponent(fifthDay)
                                .addGap(42, 42, 42)
                                .addComponent(ninethday)
                                .addGap(33, 33, 33)
                                .addComponent(sixthDay))
                            .addGroup(daysOfMonthLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(daysOfMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(monday1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(monday4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(daysOfMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(monday3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(monday2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(monday5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(daysOfMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(daysOfMonthLayout.createSequentialGroup()
                                        .addComponent(tuesday1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wednesday1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(thursday1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(friday1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saturday1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sunday1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(daysOfMonthLayout.createSequentialGroup()
                                        .addComponent(tuesday4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wednesday4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(thursday4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(friday4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saturday4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sunday4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(daysOfMonthLayout.createSequentialGroup()
                                        .addComponent(tuesday3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wednesday3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(thursday3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(friday3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saturday3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sunday3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, daysOfMonthLayout.createSequentialGroup()
                                        .addComponent(tuesday2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wednesday2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(thursday2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(friday2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saturday2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sunday2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(daysOfMonthLayout.createSequentialGroup()
                                        .addComponent(tuesday5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(wednesday5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(thursday5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(friday5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saturday5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sunday5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, daysOfMonthLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(monday6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tuesday6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wednesday6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thursday6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(friday6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saturday6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sunday6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        daysOfMonthLayout.setVerticalGroup(
            daysOfMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, daysOfMonthLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(daysOfMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstDay)
                    .addComponent(secondDay)
                    .addComponent(thirdDay)
                    .addComponent(forthDay)
                    .addComponent(fifthDay)
                    .addComponent(sixthDay)
                    .addComponent(ninethday))
                .addGap(18, 18, 18)
                .addGroup(daysOfMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monday1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saturday1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friday1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thursday1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tuesday1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wednesday1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sunday1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(daysOfMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monday2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saturday2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friday2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thursday2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tuesday2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wednesday2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sunday2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(daysOfMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monday3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saturday3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friday3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thursday3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tuesday3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wednesday3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sunday3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(daysOfMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monday4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saturday4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friday4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thursday4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tuesday4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wednesday4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sunday4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(daysOfMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monday5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saturday5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friday5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thursday5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tuesday5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wednesday5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sunday5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(daysOfMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monday6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saturday6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(friday6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thursday6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tuesday6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wednesday6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sunday6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        monthLabel.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        monthLabel.setText("                  Month");

        monthNextButton.setText("Next");
        monthNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthNextButtonActionPerformed(evt);
            }
        });

        monthPrevButton.setText("Prev");
        monthPrevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthPrevButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(daysOfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(todayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(535, 535, 535)
                        .addComponent(monthPrevButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addComponent(monthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(monthNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(monthNextButton)
                    .addComponent(monthPrevButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(todayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(daysOfMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monday1ActionPerformed
        createNewDayGui(monday1);
    }//GEN-LAST:event_monday1ActionPerformed

    private void wednesday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesday1ActionPerformed
        createNewDayGui(wednesday1);
    }//GEN-LAST:event_wednesday1ActionPerformed

    private void tuesday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesday1ActionPerformed
        createNewDayGui(tuesday1);
    }//GEN-LAST:event_tuesday1ActionPerformed

    private void saturday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturday1ActionPerformed
        createNewDayGui(saturday1);
    }//GEN-LAST:event_saturday1ActionPerformed

    private void friday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friday1ActionPerformed
        createNewDayGui(friday1);
    }//GEN-LAST:event_friday1ActionPerformed

    private void thursday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursday1ActionPerformed
        createNewDayGui(thursday1);
    }//GEN-LAST:event_thursday1ActionPerformed

    private void sunday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunday1ActionPerformed
        createNewDayGui(sunday1);
    }//GEN-LAST:event_sunday1ActionPerformed

    private void monday3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monday3ActionPerformed
        createNewDayGui(monday3);
    }//GEN-LAST:event_monday3ActionPerformed

    private void wednesday3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesday3ActionPerformed
        createNewDayGui(wednesday3);
    }//GEN-LAST:event_wednesday3ActionPerformed

    private void tuesday3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesday3ActionPerformed
        createNewDayGui(tuesday3);
    }//GEN-LAST:event_tuesday3ActionPerformed

    private void saturday3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturday3ActionPerformed
        
        createNewDayGui(saturday3);
    }//GEN-LAST:event_saturday3ActionPerformed

    private void friday3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friday3ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(friday3);
    }//GEN-LAST:event_friday3ActionPerformed

    private void thursday3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursday3ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(thursday3);
    }//GEN-LAST:event_thursday3ActionPerformed

    private void sunday3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunday3ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(sunday3);
    }//GEN-LAST:event_sunday3ActionPerformed

    private void monday2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monday2ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(monday2);
    }//GEN-LAST:event_monday2ActionPerformed

    private void wednesday2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesday2ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(wednesday2);
    }//GEN-LAST:event_wednesday2ActionPerformed

    private void tuesday2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesday2ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(tuesday2);
    }//GEN-LAST:event_tuesday2ActionPerformed

    private void saturday2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturday2ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(saturday2);
    }//GEN-LAST:event_saturday2ActionPerformed

    private void friday2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friday2ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(friday2);
    }//GEN-LAST:event_friday2ActionPerformed

    private void thursday2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursday2ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(thursday2);
    }//GEN-LAST:event_thursday2ActionPerformed

    private void sunday2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunday2ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(sunday2);
    }//GEN-LAST:event_sunday2ActionPerformed

    private void monday4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monday4ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(monday4);
    }//GEN-LAST:event_monday4ActionPerformed

    private void wednesday4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesday4ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(wednesday4);
    }//GEN-LAST:event_wednesday4ActionPerformed

    private void tuesday4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesday4ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(tuesday4);
    }//GEN-LAST:event_tuesday4ActionPerformed

    private void saturday4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturday4ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(saturday4);
    }//GEN-LAST:event_saturday4ActionPerformed

    private void friday4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friday4ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(friday4);
    }//GEN-LAST:event_friday4ActionPerformed

    private void thursday4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursday4ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(thursday4);
    }//GEN-LAST:event_thursday4ActionPerformed

    private void sunday4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunday4ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(sunday4);
    }//GEN-LAST:event_sunday4ActionPerformed

    private void monday5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monday5ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(monday5);
    }//GEN-LAST:event_monday5ActionPerformed

    private void wednesday5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesday5ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(wednesday5);
    }//GEN-LAST:event_wednesday5ActionPerformed

    private void tuesday5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesday5ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(tuesday5);
    }//GEN-LAST:event_tuesday5ActionPerformed

    private void saturday5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturday5ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(saturday5);
    }//GEN-LAST:event_saturday5ActionPerformed

    private void friday5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friday5ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(friday5);
    }//GEN-LAST:event_friday5ActionPerformed

    private void thursday5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursday5ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(thursday5);
    }//GEN-LAST:event_thursday5ActionPerformed

    private void sunday5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunday5ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(sunday5);
    }//GEN-LAST:event_sunday5ActionPerformed

    private void monthNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthNextButtonActionPerformed
        currentDate.changeCurrentMonth(1);
        prepareDaysInterface(this.listofDays);
    }//GEN-LAST:event_monthNextButtonActionPerformed

    private void monthPrevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthPrevButtonActionPerformed
        currentDate.changeCurrentMonth(-1);
        prepareDaysInterface(this.listofDays);

    }//GEN-LAST:event_monthPrevButtonActionPerformed

    private void friday6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friday6ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(friday6);
    }//GEN-LAST:event_friday6ActionPerformed

    private void thursday6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursday6ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(thursday6);
    }//GEN-LAST:event_thursday6ActionPerformed

    private void sunday6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunday6ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(sunday6);
    }//GEN-LAST:event_sunday6ActionPerformed

    private void monday6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monday6ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(monday6);
    }//GEN-LAST:event_monday6ActionPerformed

    private void wednesday6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesday6ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(wednesday6);
    }//GEN-LAST:event_wednesday6ActionPerformed

    private void tuesday6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesday6ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(tuesday6);
    }//GEN-LAST:event_tuesday6ActionPerformed

    private void saturday6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturday6ActionPerformed
        // TODO add your handling code here:
        createNewDayGui(saturday6);
    }//GEN-LAST:event_saturday6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel daysOfMonth;
    private javax.swing.JLabel fifthDay;
    private javax.swing.JLabel firstDay;
    private javax.swing.JLabel forthDay;
    private javax.swing.JButton friday1;
    private javax.swing.JButton friday2;
    private javax.swing.JButton friday3;
    private javax.swing.JButton friday4;
    private javax.swing.JButton friday5;
    private javax.swing.JButton friday6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton monday1;
    private javax.swing.JButton monday2;
    private javax.swing.JButton monday3;
    private javax.swing.JButton monday4;
    private javax.swing.JButton monday5;
    private javax.swing.JButton monday6;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JButton monthNextButton;
    private javax.swing.JButton monthPrevButton;
    private javax.swing.JLabel ninethday;
    private javax.swing.JButton saturday1;
    private javax.swing.JButton saturday2;
    private javax.swing.JButton saturday3;
    private javax.swing.JButton saturday4;
    private javax.swing.JButton saturday5;
    private javax.swing.JButton saturday6;
    private javax.swing.JLabel secondDay;
    private javax.swing.JLabel sixthDay;
    private javax.swing.JButton sunday1;
    private javax.swing.JButton sunday2;
    private javax.swing.JButton sunday3;
    private javax.swing.JButton sunday4;
    private javax.swing.JButton sunday5;
    private javax.swing.JButton sunday6;
    private javax.swing.JLabel thirdDay;
    private javax.swing.JButton thursday1;
    private javax.swing.JButton thursday2;
    private javax.swing.JButton thursday3;
    private javax.swing.JButton thursday4;
    private javax.swing.JButton thursday5;
    private javax.swing.JButton thursday6;
    private javax.swing.JLabel todayDateLabel;
    private javax.swing.JLabel todayLabel;
    private javax.swing.JPanel todayPanel;
    private javax.swing.JButton tuesday1;
    private javax.swing.JButton tuesday2;
    private javax.swing.JButton tuesday3;
    private javax.swing.JButton tuesday4;
    private javax.swing.JButton tuesday5;
    private javax.swing.JButton tuesday6;
    private javax.swing.JButton wednesday1;
    private javax.swing.JButton wednesday2;
    private javax.swing.JButton wednesday3;
    private javax.swing.JButton wednesday4;
    private javax.swing.JButton wednesday5;
    private javax.swing.JButton wednesday6;
    // End of variables declaration//GEN-END:variables
}
